language: java
services:
  - docker
jdk:
  - openjdk11
jobs:
  include:
    - stage: checkstyle
      script:
        - ./gradlew check
    - stage: build
      script:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - "./gradlew -PimageName=$IMAGE_NAME -Ptag=$VERSION_TAG buildDocker"
        - eval $(aws ecr get-login --no-include-email)
        - docker push $IMAGE_NAME:$VERSION_TAG
    - stage: deploy
      script:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - bin/deploy
stages:
  - checkstyle
  - build
  - name: deploy
    if: branch = master
notifications:
  email: false
  slack:
    secure: Pp5UD5u5uRTDgSDmfh9y1OaMPW9Xs1Spy3wnFOBlKZQedw/r/jmT2Cb/lhxoQ5M6mSdBRKbZ7Zf1aHv2g3yf7m/k0eZvLo3PEMWMEv5XQWTB7RxE50q9tL5e7eNG8K9Vq3si2bIuHV4C2tBxklCFLYuEBHLcCI7iYz0zWHuGQWdCuCGIogvvcsdYpUXsVHTAirE+3Xw4CvaHfL17QKH4OlkjCgApqgVAdyz2dOPIlypoCwkvSnrw7k3gIGLmMXj/UrWffaXSPm5ISXSqzsATh/eZs2Ru6hz44I9u+/+WUQSKwqJxEbx8S1a17F0L4z9B6Kfbj2LaCrGWbe7s+42skmQlDsITnicXt49ZdWlaLM2Qtnkjm2cv78E7GVgPXuaCmeEQ+N39Krc17HRcG1WAYM3XAjIs2JcZKEBgBjbg3iyeB/z8y5CgLPex/npbzlbenh+N/zgXjwH/v9GKwkObSGpBp8RRImKSUzaRoMkW2xt81e6YHLEwwmNNd6/yjsvjJ8SVkVxtlX76ej4CqB+G0WXUTOi+kN4OPBHwvOx0Ctt77Snn/fDDTQYZkBW719Of6Plp9Aj+rlYl3o++KEX/x/u1Ec5HomHliy+eEudgBzN3uESsL6Pz5pVWMLQg9+WBdaa1rVhAWgtrk/ZHHmTMhLj/FObdxQc9kZzZS95ruDY=
env:
  global:
    - VERSION_TAG=$(echo $TRAVIS_COMMIT | head -c 8)
    - secure: CoG4OF1VkfeWBXta5dSXHu/oiGD/FhhnGfO4oHgli2ZXfKV9st8Vu6uqzh1kuH7aHv6TzD0XIJBVerXRfrT8m73+aCvtf3v4Bu8dqZkG5ns/zGdVXHW4uq3OAtDnoRZ2zNsabyAwzZ3SsbbqrHJazvezYs5Og75LNV6iJSBvEIJA7iVMaYfJfToP+hs9eZ+0V62KMsUfC6jJqTfWsGsZV8DljokUlvy873NiuoYXNJ0maOe6leTsELNuW2K5GNd2LqgX1KtfD85WN92U0nZcJmsilWBUblwajggUUygfcAaBKEWpJ18q3l3pR5nZn+1zz6lDMp/8EUT770IV+ubVh2z4wGi0LOBQu5g0UUqPB14POC7fNPj/wmuYAYouS1GQelks2ahKnCTJGvC0jh/+EBDmSK4h10uZZT1y8RQn8li3PBZCs2Wk5pP5COqt6zbtV0xLzUgKu71OR8neOwz5CXENIcddshi4smMBWBBUMJlrOvlkqKKXPM3bzTgKIkFEnGO4MP0M4zw/czKqGBo7qI7nFYm6x7hHW04QvVeMc6lrUBxOY+IvibsAcQ4bC6N78TI8vsp8z+F6DHkRN4BRDf+TuG7fJ/7kN7tl2Vz3Mxo8iL6In08Joj1RuAtah6/t2lgFNm8eITMfp6wL54RTlEpqh2TE9MEPlYmcggW6z54=
    - secure: j27tJJErGCgRSk43jzRi9tR3Z6ENsr9bR2PZqVxwzWF9uadbe9bSSBMxRRljFPbcpTg/NK+N932Tww2wEK2rWt+H/3mI8F/1Q283RTWvNY+gBXF0rHTWQbleVJ5y3VLxRXKeSfLxILh8aQjw8/jwRqZhbwPelug2cRnzKx3n7MC4nOKRrHB8HPxZ32znoLNszBXxx5rYWAqAxTP8V5FpHxe8NC216AYKnrM2Lo2p0BlXqppgvFkWr9dphmBQ/s6/yB69Hitf0N0VUNa99ssRTMehTQBM9Ejzr6ZpjkEsZ/q7qj65NKvfhC7ekC1YD+ogdXfUfwvoeTBrL2Ra3tasAMwPS8Y4VuXHcnC0OFano5t3EqXNznq/Jupki9glw8oMmVI4VYhDbHlrGCDU5w6o1xJKkutwYDURxub4CV5rnRNIT7uwWhTQ3YgiGfLkaEbrc3ZSjF00zQ8JDkGUM4jfT6FPhXg0++vMnnI7ONMstgsPPCsUPjfEO90mKiOZh4BheEcoWCNme6jYI5gzqbbIV5STCZGbDdEwSAcdPt+DvNp6/hv1pvAq42Zf7BGJg1jx2U7j6kztrd+JOcfUx8VAQ+lBhlHTi1nMXf/NUuOgTpYPnaHZT9W7IBBPpEfYZM9oksbxxZDflIVIOwqx1e6aezDASU1wCS/Z74Slb3Qmdvs=
    - secure: iwA2PkBsrqW7VbMCBHiyE63mDe+7AFGzqUdXaXkfCg+WrJ0DpfgDaIMGmAnbALiH40g4oUCGDdczf8OcHKFDgTv6gdXCk26RZS+nb+jOqDQa3yyR9aADXjG02ciLahWCv18pj3Zjt6vdu2m2xTx/TL7iJLAsdcJ3GOsR9GuBOlf1QdO8zcksLmDiKWQyNXexKmhVAwVQ1nfDFFWbccKO9zRo3Utcowm8LHs7X8NiWMfpSpetK4R2rmci6GUFOgoDhf5w1v0fPvhtPVOxKQXAEU0RH0wmBzZ+3vIhYFZmX+Oj43KwczyMMw+26ywzXt6022tLzzZRocKh0NxC0tGETC6Hy7VceypCFUtQxUSFhy54UVMCjPwSCCUnzpfXLHLl4t4vmPEBg50ph9QIHWp4QLta3waAh+RJ5dlVy5AClJ7aYHvlfccNO5ClHhT4vvNFjISrquYIiuoTinWRP+5/jUEqEMl3LvWjqA+vkXw5Bw1XobcXN9UZUmEq9OnWvhjLA9zev5JZpA8ogTFzcJMxjMVjAs5x3nMMvkbBVMXlZd3jMHaf3AROMTdXKkP3ommRrXuCwIOz0UXKTKLhEZ2IQ1fGYi9OV1GC3pXdli/gg7x2Dy8aKF/rZGMEVjtOhCMeDFvzjLGyIDUIPOAvRg3NtCn2LVpCHETkcU5cYTfxCIk=
    - secure: P6v+WOZJzz29prYUu4Qk0+KICBB+Bd7QbwuT7+LQEjesyANKwpJwHjsY87uhfliMsYDZg5S4QqdFWB1G24mdjIm3/v5TjNzfQT1ZoEiuyGZpp9GqG0FoCtHoajVRENYxV6GpoYQgRkN34UemWHFdOaSDgbM/2738TNZQBI6w0yJtL6SsBmkIq8lBLtWNdzhiqOcgE23w/2kf5pJKPFyDA8Y3V/VZYtXeQbJTUtGnWwglm4utv7GIE5r60dmlut5ZJwFjgq45tR4JYXMBze+Z2jsgTtpJFFnicX7PHYCicndH9u0J50Nt8d4W2ApSASNhJ3IuaJHuTQ4htV0Ypjd3vif1Pimc5cZC4Fq9GAiKrwFb4W0HpOrlcu0MN22m52rIBWtf0+gN/XFUfmP6RwesxR66tUsWyTEHdg6EXY69wp1b8x7MNgUlW7lQ4TKiZzICuoyAroeEUF7uUWvOi8+wZL1/M3j5yABvTJ3CJ1w9a759/3OaKZZBvXsOelGQpAZgPavK7wyr0v76j5M9ZyvAJKhDyJ1HjXOgYiwqrBIJoTD7dMgNkfrRi2+RiR8wsnaqAfj7HTFuzAhv7Q7X2gGJuJOu0vea9Aiqu4iqSAjXYemiGrwXMWoPT3Wj8CXf319Lcq4eBgckkuzNRbjFOjfCWkyS5zJMHDmqmdB3XtA4SLs=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
